# Generated by Django 3.1.6 on 2021-02-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentround',
            name='tags',
        ),
    ]
