# Generated by Django 3.1.6 on 2021-02-15 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0002_remove_commentround_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRoundTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, null=True)),
                ('comment_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dmm.commentround')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dmm.tag')),
            ],
        ),
        migrations.AddField(
            model_name='commentround',
            name='tags',
            field=models.ManyToManyField(through='dmm.CommentRoundTags', to='dmm.Tag'),
        ),
    ]
