# Generated by Django 3.1.6 on 2021-02-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0002_auto_20210223_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentround',
            name='create_date',
        ),
        migrations.AddField(
            model_name='commentround',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
