# Generated by Django 3.1.6 on 2021-02-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0003_auto_20210223_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publications',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.RemoveField(
            model_name='language',
            name='programmer',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
