# Generated by Django 3.1.6 on 2021-02-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0003_auto_20210215_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentroundtags',
            name='is_present',
            field=models.BooleanField(null=True),
        ),
    ]
