# Generated by Django 3.1.6 on 2021-02-15 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0004_auto_20210215_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentroundtags',
            name='comment_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dmm.commentround'),
        ),
        migrations.AlterField(
            model_name='commentroundtags',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dmm.tag'),
        ),
    ]
