# Generated by Django 3.1.6 on 2021-02-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0005_auto_20210215_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
    ]
