# Generated by Django 3.1.6 on 2021-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0005_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentround',
            name='tags',
            field=models.ManyToManyField(blank=True, through='dmm.CommentRoundTags', to='dmm.Tag'),
        ),
    ]
