# Generated by Django 3.1.6 on 2021-02-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0007_auto_20210215_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
