# Generated by Django 3.1.6 on 2021-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0007_auto_20210303_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
