# Generated by Django 3.1.6 on 2021-02-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0008_auto_20210218_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
