# Generated by Django 3.1.6 on 2021-03-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0008_auto_20210303_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='clarification',
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
