# Generated by Django 3.1.6 on 2021-03-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0009_auto_20210303_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='icon_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
