# Generated by Django 3.1.6 on 2021-02-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0009_auto_20210218_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='create_date',
        ),
        migrations.AddField(
            model_name='result',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
