# Generated by Django 3.1.6 on 2021-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmm', '0010_auto_20210305_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
